
CREATE TABLE IF NOt EXISTS song
(
    id BIGSERIAL PRIMARY KEY,
    artist VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
);


INSERT INTO song (id, artist, name) VALUES
                                        (nextval('song_id_seq'), 'Metallica', 'Enter Sandman'),
                                        (nextval('song_id_seq'), 'Metallica', 'Nothing Else Matters'),
                                        (nextval('song_id_seq'), 'Nirvana', 'Smells Like Teen Spirit'),
                                        (nextval('song_id_seq'), 'Nirvana', 'Come As You Are'),
                                        (nextval('song_id_seq'), 'Pink Floyd', 'Wish You Were Here'),
                                        (nextval('song_id_seq'), 'Pink Floyd', 'Comfortably Numb'),
                                        (nextval('song_id_seq'), 'Queen', 'Bohemian Rhapsody'),
                                        (nextval('song_id_seq'), 'Queen', 'Don’t Stop Me Now'),
                                        (nextval('song_id_seq'), 'AC/DC', 'Back In Black'),
                                        (nextval('song_id_seq'), 'AC/DC', 'Highway to Hell'),
                                        (nextval('song_id_seq'), 'The Beatles', 'Hey Jude'),
                                        (nextval('song_id_seq'), 'The Beatles', 'Let It Be'),
                                        (nextval('song_id_seq'), 'Red Hot Chili Peppers', 'Californication'),
                                        (nextval('song_id_seq'), 'Red Hot Chili Peppers', 'Scar Tissue'),
                                        (nextval('song_id_seq'), 'U2', 'With or Without You'),
                                        (nextval('song_id_seq'), 'U2', 'Beautiful Day'),
                                        (nextval('song_id_seq'), 'Coldplay', 'Yellow'),
                                        (nextval('song_id_seq'), 'Coldplay', 'Fix You'),
                                        (nextval('song_id_seq'), 'Linkin Park', 'In the End'),
                                        (nextval('song_id_seq'), 'Linkin Park', 'Numb'),
                                        (nextval('song_id_seq'), 'Eminem', 'Lose Yourself'),
                                        (nextval('song_id_seq'), 'Eminem', 'Stan'),
                                        (nextval('song_id_seq'), 'Imagine Dragons', 'Radioactive'),
                                        (nextval('song_id_seq'), 'Imagine Dragons', 'Demons'),
                                        (nextval('song_id_seq'), 'Adele', 'Hello'),
                                        (nextval('song_id_seq'), 'Adele', 'Rolling in the Deep'),
                                        (nextval('song_id_seq'), 'Daft Punk', 'Get Lucky'),
                                        (nextval('song_id_seq'), 'Daft Punk', 'One More Time'),
                                        (nextval('song_id_seq'), 'The Weeknd', 'Blinding Lights'),
                                        (nextval('song_id_seq'), 'The Weeknd', 'Save Your Tears'),
                                        (nextval('song_id_seq'), 'Taylor Swift', 'Shake It Off'),
                                        (nextval('song_id_seq'), 'Taylor Swift', 'Blank Space'),
                                        (nextval('song_id_seq'), 'Ed Sheeran', 'Shape of You'),
                                        (nextval('song_id_seq'), 'Ed Sheeran', 'Perfect'),
                                        (nextval('song_id_seq'), 'Kanye West', 'Stronger'),
                                        (nextval('song_id_seq'), 'Kanye West', 'Power'),
                                        (nextval('song_id_seq'), 'Drake', 'God’s Plan'),
                                        (nextval('song_id_seq'), 'Drake', 'Hotline Bling'),
                                        (nextval('song_id_seq'), 'Bruno Mars', 'Uptown Funk'),
                                        (nextval('song_id_seq'), 'Bruno Mars', '24K Magic'),
                                        (nextval('song_id_seq'), 'Rihanna', 'Diamonds'),
                                        (nextval('song_id_seq'), 'Rihanna', 'Umbrella'),
                                        (nextval('song_id_seq'), 'Maroon 5', 'Sugar'),
                                        (nextval('song_id_seq'), 'Maroon 5', 'Memories'),
                                        (nextval('song_id_seq'), 'Oasis', 'Wonderwall'),
                                        (nextval('song_id_seq'), 'Oasis', 'Don’t Look Back in Anger'),
                                        (nextval('song_id_seq'), 'Foo Fighters', 'Everlong'),
                                        (nextval('song_id_seq'), 'Foo Fighters', 'The Pretender');
